### ISSUE TITLE
Ошибка при установки modx

### ISSUE THREAD

**Issue by alexsoin** [pavel-one/DevDocker#1]
Запуская `make init` зависает на этапе `Building app` и при этом в процессе выводятся ошибки `Отказано в доступе`:

```
Генерируем nginx конфигурации
Выбран MODX
bin/init.sh: строка 43: ./conf/nginx/project.conf: Отказано в доступе
bin/init.sh: строка 48: docker-compose.yml: Отказано в доступе
Вам нужна автоматическая установка фреймворка в папку ./app [yes/no]:
 Внимание! Это удалит ваш дамп БД и все файлы в папке ./app
yes
Очищаем папку app
Устанавливаем MODX
Копируем чистую базу данных
Building app
```

И несовсем понятно, как вручную загрузить бд.

---

Система: **ubuntu 19.10**

**Comment by pavel-one** [comment]
Скорее всего ты запускал sudo make init до этого и он создал файлы от рута, а потом когда ты запустил без sudo скрипт не может удалить вышеперечисленные файлы, можно удалить вручную

> И несовсем понятно, как вручную загрузить бд.  

Есть несколько способов, 
1. удаляешь папку ./db если она была создана и заменяешь файл ./dump/dump.sql
2. `docker-compose exec db mysql -u db_user -pX5NasAOm db < path/to/dump.sql`

**Comment by alexsoin** [comment]
Клонировал заново репозиторий, запустил `make init`, всё прошло успешло:
![изображение](https://user-images.githubusercontent.com/3787132/80573672-7168eb80-8a11-11ea-8d5c-b8e7530dbead.png)

Но, при запуске показывается ошибка:

![изображение](https://user-images.githubusercontent.com/3787132/80573640-5d24ee80-8a11-11ea-9799-212afa771a36.png)

**Comment by alexsoin** [comment]
Странно, через минуту заработало)))

![изображение](https://user-images.githubusercontent.com/3787132/80577392-de7f7f80-8a17-11ea-9ca6-8f67691ec7c5.png)

**Comment by alexsoin** [comment]
А как можно настроить работу phpStorm на работу с бд devDocker?

**Comment by pavel-one** [comment]
> Странно, через минуту заработало)))

Базе данных нужно время чтобы развернуться, она разворачивается в фоне, скорость разворачивания зависит от твоей системы, видимо минута - это задержка твоей системы)

> А как можно настроить работу phpStorm на работу с бд devDocker?

Чуть позже отвечу в соседнем issue пришлю ссылку сюда

**Comment by pavel-one** [comment]
Сделал документацию, закрываю ишью https://github.com/pavel-one/DevDocker/blob/master/doc/db.md
